//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThePrinterSpyControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Id { get; set; }
        public byte AdEnabled { get; set; }
        public string AdServer { get; set; }
        public string AdUser { get; set; }
        public string AdPassword { get; set; }
        public string AdDn { get; set; }
    }
}
