//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThePrinterSpyControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintData
    {
        public int Id { get; set; }
        public int PrinterId { get; set; }
        public int UserId { get; set; }
        public int ComputerId { get; set; }
        public int ServerId { get; set; }
        public string DocName { get; set; }
        public int Pages { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int JobId { get; set; }
    }
}
