//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThePrinterSpyControl.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThePrinterSpyControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string AboutButtonClose {
            get {
                return ResourceManager.GetString("AboutButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home page.
        /// </summary>
        public static string AboutLabelHomePage {
            get {
                return ResourceManager.GetString("AboutLabelHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Printer Spy.
        /// </summary>
        public static string AboutLabelProgramName {
            get {
                return ResourceManager.GetString("AboutLabelProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string AboutLabelVersion {
            get {
                return ResourceManager.GetString("AboutLabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string ButtonPrinterDelete {
            get {
                return ResourceManager.GetString("ButtonPrinterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename.
        /// </summary>
        public static string ButtonPrinterRename {
            get {
                return ResourceManager.GetString("ButtonPrinterRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        public static string CheckPrinterEnabled {
            get {
                return ResourceManager.GetString("CheckPrinterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum Value Length - 1.
        /// </summary>
        public static string ConfigADPasswordLengthError {
            get {
                return ResourceManager.GetString("ConfigADPasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum Value Length - 5.
        /// </summary>
        public static string ConfigADServerLengthError {
            get {
                return ResourceManager.GetString("ConfigADServerLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server Name Format Error. Must be: &apos;XX.YY[Z]&apos;.
        /// </summary>
        public static string ConfigADServerValueError {
            get {
                return ResourceManager.GetString("ConfigADServerValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum Value Length - 2.
        /// </summary>
        public static string ConfigADUserLengthError {
            get {
                return ResourceManager.GetString("ConfigADUserLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synchronize all users.
        /// </summary>
        public static string ConfigButtonADSync {
            get {
                return ResourceManager.GetString("ConfigButtonADSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        public static string ConfigCheckADEnabled {
            get {
                return ResourceManager.GetString("ConfigCheckADEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        public static string ConfigCheckMaskEnabled {
            get {
                return ResourceManager.GetString("ConfigCheckMaskEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        public static string ConfigCheckReportPeriodEnabled {
            get {
                return ResourceManager.GetString("ConfigCheckReportPeriodEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synchronization with Active Directory.
        /// </summary>
        public static string ConfigGroupADTitle {
            get {
                return ResourceManager.GetString("ConfigGroupADTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Printer Name Mask.
        /// </summary>
        public static string ConfigGroupPrinterNameMaskTitle {
            get {
                return ResourceManager.GetString("ConfigGroupPrinterNameMaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report Period.
        /// </summary>
        public static string ConfigGroupReportPeriodTitle {
            get {
                return ResourceManager.GetString("ConfigGroupReportPeriodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain.
        /// </summary>
        public static string ConfigLabelADDomain {
            get {
                return ResourceManager.GetString("ConfigLabelADDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string ConfigLabelADPassword {
            get {
                return ResourceManager.GetString("ConfigLabelADPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Name.
        /// </summary>
        public static string ConfigLabelADUser {
            get {
                return ResourceManager.GetString("ConfigLabelADUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mask Type.
        /// </summary>
        public static string ConfigLabelMaskType {
            get {
                return ResourceManager.GetString("ConfigLabelMaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mask.
        /// </summary>
        public static string ConfigLabelMaskValue {
            get {
                return ResourceManager.GetString("ConfigLabelMaskValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End.
        /// </summary>
        public static string ConfigLabelReportPeriodEnd {
            get {
                return ResourceManager.GetString("ConfigLabelReportPeriodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Begin.
        /// </summary>
        public static string ConfigLabelReportPeriodStart {
            get {
                return ResourceManager.GetString("ConfigLabelReportPeriodStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Period Type.
        /// </summary>
        public static string ConfigLabelReportPeriodType {
            get {
                return ResourceManager.GetString("ConfigLabelReportPeriodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The field value must be &quot;1&quot; or greater.
        /// </summary>
        public static string ConfigMaskValueError {
            get {
                return ResourceManager.GetString("ConfigMaskValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The field length must be &quot;1&quot; or greater.
        /// </summary>
        public static string ConfigPrinterNameValueError {
            get {
                return ResourceManager.GetString("ConfigPrinterNameValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string ConfigWindowsButtonCancel {
            get {
                return ResourceManager.GetString("ConfigWindowsButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string ConfigWindowsButtonOk {
            get {
                return ResourceManager.GetString("ConfigWindowsButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Config.
        /// </summary>
        public static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;noname&gt;.
        /// </summary>
        public static string DepartmentNoName {
            get {
                return ResourceManager.GetString("DepartmentNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export Error.
        /// </summary>
        public static string ExportErrorTitle {
            get {
                return ResourceManager.GetString("ExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excel error: make sure the Excel is installed on your computer.
        /// </summary>
        public static string ExportExcelErrorMessage {
            get {
                return ResourceManager.GetString("ExportExcelErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Printer Spy - Control Panel.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tab [Computers].
        /// </summary>
        public static string MenuComputersShow {
            get {
                return ResourceManager.GetString("MenuComputersShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Config.
        /// </summary>
        public static string MenuConfig {
            get {
                return ResourceManager.GetString("MenuConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tab [Departments].
        /// </summary>
        public static string MenuDepartmentsShow {
            get {
                return ResourceManager.GetString("MenuDepartmentsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Options.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tab [Printers].
        /// </summary>
        public static string MenuPrintersShow {
            get {
                return ResourceManager.GetString("MenuPrintersShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export Report....
        /// </summary>
        public static string MenuReportExport {
            get {
                return ResourceManager.GetString("MenuReportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tab [Users].
        /// </summary>
        public static string MenuUsersShow {
            get {
                return ResourceManager.GetString("MenuUsersShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Config.
        /// </summary>
        public static string NavConfig {
            get {
                return ResourceManager.GetString("NavConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string NavRefresh {
            get {
                return ResourceManager.GetString("NavRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export Report....
        /// </summary>
        public static string NavReportExport {
            get {
                return ResourceManager.GetString("NavReportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computer.
        /// </summary>
        public static string ReportComputer {
            get {
                return ResourceManager.GetString("ReportComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date-Time.
        /// </summary>
        public static string ReportDateTime {
            get {
                return ResourceManager.GetString("ReportDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Document Name.
        /// </summary>
        public static string ReportDocument {
            get {
                return ResourceManager.GetString("ReportDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages.
        /// </summary>
        public static string ReportPages {
            get {
                return ResourceManager.GetString("ReportPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [all time].
        /// </summary>
        public static string ReportPeriodAllTime {
            get {
                return ResourceManager.GetString("ReportPeriodAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Day.
        /// </summary>
        public static string ReportPeriodTypeCurrentDay {
            get {
                return ResourceManager.GetString("ReportPeriodTypeCurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Month.
        /// </summary>
        public static string ReportPeriodTypeCurrentMonth {
            get {
                return ResourceManager.GetString("ReportPeriodTypeCurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Week.
        /// </summary>
        public static string ReportPeriodTypeCurrentWeek {
            get {
                return ResourceManager.GetString("ReportPeriodTypeCurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Year.
        /// </summary>
        public static string ReportPeriodTypeCurrentYear {
            get {
                return ResourceManager.GetString("ReportPeriodTypeCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manual Defined (Date-Date).
        /// </summary>
        public static string ReportPeriodTypeFromDateToDate {
            get {
                return ResourceManager.GetString("ReportPeriodTypeFromDateToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From Date To Now.
        /// </summary>
        public static string ReportPeriodTypeFromDateToNow {
            get {
                return ResourceManager.GetString("ReportPeriodTypeFromDateToNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 180 Days.
        /// </summary>
        public static string ReportPeriodTypeLast180Days {
            get {
                return ResourceManager.GetString("ReportPeriodTypeLast180Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 30 Days.
        /// </summary>
        public static string ReportPeriodTypeLast30Days {
            get {
                return ResourceManager.GetString("ReportPeriodTypeLast30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 7 Days.
        /// </summary>
        public static string ReportPeriodTypeLast7Days {
            get {
                return ResourceManager.GetString("ReportPeriodTypeLast7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous Day.
        /// </summary>
        public static string ReportPeriodTypePreviousDay {
            get {
                return ResourceManager.GetString("ReportPeriodTypePreviousDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous Month.
        /// </summary>
        public static string ReportPeriodTypePreviousMonth {
            get {
                return ResourceManager.GetString("ReportPeriodTypePreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous Week.
        /// </summary>
        public static string ReportPeriodTypePreviousWeek {
            get {
                return ResourceManager.GetString("ReportPeriodTypePreviousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous Year.
        /// </summary>
        public static string ReportPeriodTypePreviousYear {
            get {
                return ResourceManager.GetString("ReportPeriodTypePreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Printer.
        /// </summary>
        public static string ReportPrinter {
            get {
                return ResourceManager.GetString("ReportPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of Chars from the String Beginning.
        /// </summary>
        public static string ReportPrinterNameBeginName {
            get {
                return ResourceManager.GetString("ReportPrinterNameBeginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contains Symbols....
        /// </summary>
        public static string ReportPrinterNameContainsName {
            get {
                return ResourceManager.GetString("ReportPrinterNameContainsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of Chars from the String End.
        /// </summary>
        public static string ReportPrinterNameEndName {
            get {
                return ResourceManager.GetString("ReportPrinterNameEndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regular Expresion.
        /// </summary>
        public static string ReportPrinterNameRegexpName {
            get {
                return ResourceManager.GetString("ReportPrinterNameRegexpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Original Name (full value).
        /// </summary>
        public static string ReportPrinterNameWholeName {
            get {
                return ResourceManager.GetString("ReportPrinterNameWholeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string ReportUser {
            get {
                return ResourceManager.GetString("ReportUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computer(s).
        /// </summary>
        public static string StatusComputers {
            get {
                return ResourceManager.GetString("StatusComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Department(s).
        /// </summary>
        public static string StatusDepartments {
            get {
                return ResourceManager.GetString("StatusDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Printer(s).
        /// </summary>
        public static string StatusPrinters {
            get {
                return ResourceManager.GetString("StatusPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User(s).
        /// </summary>
        public static string StatusUsers {
            get {
                return ResourceManager.GetString("StatusUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report Period.
        /// </summary>
        public static string SummaryReportPeriod {
            get {
                return ResourceManager.GetString("SummaryReportPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summary.
        /// </summary>
        public static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Documents Printered.
        /// </summary>
        public static string SummaryTotalDocuments {
            get {
                return ResourceManager.GetString("SummaryTotalDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages Printered.
        /// </summary>
        public static string SummaryTotalPages {
            get {
                return ResourceManager.GetString("SummaryTotalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computers.
        /// </summary>
        public static string TabComputers {
            get {
                return ResourceManager.GetString("TabComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Departments.
        /// </summary>
        public static string TabDepartments {
            get {
                return ResourceManager.GetString("TabDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Printers.
        /// </summary>
        public static string TabPrinters {
            get {
                return ResourceManager.GetString("TabPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users.
        /// </summary>
        public static string TabUsers {
            get {
                return ResourceManager.GetString("TabUsers", resourceCulture);
            }
        }
    }
}
