//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThePrinterSpyControl.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public int ComputerId { get; set; }
        public int ServerId { get; set; }
        public bool Enabled { get; set; }
    }
}
